commit mongo code, user data and routes, server
GraceMattern/CS-546-Project pull request #2
Opened 2021-11-10 01:11 UTC by GraceMattern

2021-11-11 19:39 UTC, maorm200 commented on data/users.js
> +    for (let i = 0; i < userList.length; i++) {
Maybe you can simplify the for loop to a for(let x of userList) type of loop

2021-11-11 19:41 UTC, maorm200 requested changes
Added just one comment on code, rest looks fine!

2021-11-11 23:35 UTC, GraceMattern commented on data/users.js
> +    for (let i = 0; i < userList.length; i++) {
Implemented
0. changed for loop to for in loop
1. refined isEmail to include banks that are longer than one word
2. removed age restrictions in isAdult since account collection will lookup age and then allow certain account types 
3. added userId to user schema

2021-11-11 23:36 UTC, GraceMattern commented on data/users.js
> +    for (let i = 0; i < userList.length; i++) {
Implemented

2021-11-11 23:36 UTC, GraceMattern commented
1. refined isEmail to include banks that are longer than one word
2. removed age restrictions in isAdult since account collection will lookup age and then allow certain account types 
3. added userId to user schema

2021-11-12 00:28 UTC, maorm200 requested changes
```
for (let i in userList) {
        userList[i]._id = userList[i]._id.toString(); 
    }
```

Just be careful as you still need to change inside the for loop you no longer need [i] as you no longer are using the former loop.

2021-11-15 15:57 UTC, GraceMattern commented
> ```
> for (let i in userList) {
>         userList[i]._id = userList[i]._id.toString(); 
>     }
> ```
> 
> Just be careful as you still need to change inside the for loop you no longer need [i] as you no longer are using the former loop.

like this?
```
for (let i of userList) {
        i._id = i._id.toString(); 
```

2021-11-15 18:39 UTC, maorm200 commented
Yes, that is correct!

2021-11-15 18:40 UTC, merged